language: python
python:
  - "2.7"

sudo: false

env:
  global:
    - PIP_FIND_LINKS=file://$HOME/.cache/pip
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - TOX_ENV=py27-hg3.7

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis McTravis"
  - cp lib/python/mozilla_buildtools/test/hgrc ~/.hgrc

install:
  - pip install tox==1.9.2

script:
  - tox -e $TOX_ENV
  # Remove logs to avoid cache uploads
  - rm -rf $HOME/.cache/pip/log

after_script:
  - tox -e py27-coveralls

# The channel name "irc.mozilla.org#releng-bots" is encrypted against mozilla/build-tools to prevent IRC spam of forks
notifications:
  irc:
    channels:
      - secure: m+ABHaHZWh9VW1jpiuODPKiTR+tChw6XqLITKQ5tNu/RR0drwKgFdJ5PVqgErG1Fgg3to6Gp+h6xSWn2wZ4uDq4n4+fiPe1+nDreaSObLKVcY84iwkbtM5Ecr3N8LNdGENl+a79sgwGF8vX5EJQYwOW4oWFGSP4sNQ49RIJU784=
    on_success: always
    on_failure: always
    template:
      - "\x02%{repository_name}\x0314#%{build_number}\x03\x02 (%{branch} - %{commit} : %{author}): \x02\x0312%{message}\x02\x03 (\x0314%{build_url}\x03)"
